server:
  port: ${PORT:8080}

spring:
  jackson:
    property-naming-strategy: "SNAKE_CASE"
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false